from OptTensor import OptTensor
import numpy as np

def header(heading: str) -> str:
    return '-'*5 + heading + '-'*5
init = np.random.randn(2, 5)
data = np.random.randn(3, 2)
x = OptTensor(init)
y = x(data)
rl = y.relu()
rl.backward()
print(header('init'))
print(init)
print(header('data'))
print(data)
print(header('gradient'))
print(header('rl.grad'))
print(rl.grad)
print(header('rl'))
print(rl.data)
print(header('y'))
print(y.data)
print(header('y.grad'))
print(y.grad)
print(header('x.grad'))
print(x.grad)
x.data += 0.1*x.grad
y = x(data)
rl = y.relu()
rl.backward()
print(header('gradient'))
print(header('rl.grad'))
print(rl.grad)
print(header('rl'))
print(rl.data)
print(header('y'))
print(y.data)
print(header('y.grad'))
print(y.grad)
print(header('x.grad'))
print(x.grad)
